name: Create release

on: 
  push:
    tags:
    - '*'

jobs:
  deploy-container:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: current_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Get previous tag name
        id: previous_tag
        run: echo "::set-output name=TAGNAME::$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))"
      - name: 'Generate release notes'
        id: releasenotes
        run: |
          release=$(git log --pretty=format:"* %an: %s" ${{ steps.current_tag.outputs }}...${{ steps.previous_tag.outputs }})
          echo 'RELEASE_BODY<<EOF' >> $GITHUB_ENV
          echo "${release}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: 'Generate release'
        uses: ncipollo/release-action@v1
        with:
          body: ${{ env.RELEASE_BODY }}
          token: ${{ secrets.TOKEN }}